[project]
name = "label_app"
version = "0.0.1"
dependencies = [
    "streamlit>=1.35",
    "pydantic[email]",
    "streamlit-cookies-controller",
    "PyYAML",
    "PyJWT",
    "Authlib",
    "GitPython>=3.1"
]
