admin_email: viktoroo.sch@gmail.com

#projects:
#  test: https://github.com/viktor-shcherb/test-dataset/tree/master/test_project
#  also_test: https://github.com/viktor-shcherb/test-dataset/tree/master/another_project
#  semibroken_test: https://github.com/viktor-shcherb/test-dataset/tree/master/semibroken_project
#  broken_test: https://github.com/viktor-shcherb/test-dataset/tree/master/broken_project
#  private_test: https://github.com/viktor-shcherb/private-test-dataset/tree/master/project